language: ruby
branches:
  only:
    - master
dist: xenial
before_install:
- which cmake
- git clone https://github.com/swig/swig.git
- cd swig && ./autogen.sh && ./configure && make
- sudo make install
- cd ../
- rvm install 2.5.8
- rvm install 2.6.6
- rvm install 2.7.1
- if [ "TRAVIS_OS_NAME" == "linux" ]; then
  gem install bundler -v 1.17.3;
  fi
os:
- linux
- osx
rvm:
- 2.5.8
- 2.6.6
- 2.7.1
script:
- which cmake
- cd ext; rake; cd ..
- rake
- yardoc lib/*  --output-dir docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.con dashboard
  local_dir: docs
  on:
    branch: master
